@url = https://literate-waffle-5vg99j9qjxhrp9-8080.app.github.dev/alunos

POST {{url}}
Content-Type: application/json

{
    "nome" : "Antônio",
    "idade" : 22
}

###
GET {{url}}

###
GET {{url}}/4

###
PUT {{url}}/4
Content-Type: application/json

{
    "nome" : "Ana",
    "idade" : 30
}

###
DELETE {{url}}/2