@url = https://literate-waffle-5vg99j9qjxhrp9-8080.app.github.dev/tarefas

POST {{url}}
Content-Type: application/json

{
    "id" : 2,
    "descricao" : "Novo Teste"
}

###
GET {{url}}

###
PUT {{url}}/2
Content-Type: application/json

{
    "descricao" : "Teste Alterado"
}

###
DELETE {{url}}/2

###
GET {{url}}/10